googleAnalytics: G-S18R7YECZP
disqusShortname: aminrbg

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    comments: true

services:
    googleAnalytics:
        id: G-S18R7YECZP
